# Uncomment the following line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'IM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourProjectName
  # Add your dependencies here, for example:
  # pod 'Alamofire', '~> 5.4'

  pod 'CocoaAsyncSocket'

end
